spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${PLATFORM_EMAIL_USERNAME}
    password: ${PLATFORM_EMAIL_FROM_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true            # 필수: SMTP 인증을 사용함
          starttls:
            enable: true        # 필수: STARTTLS 암호화 연결을 켬
            required: true      # 필수: 암호화 연결이 안 되면 메일을 보내지 않음



platform:
  email:
    from: ${PLATFORM_EMAIL_FROM:noreply@platform.com}
    from-name: ${PLATFORM_EMAIL_FROM_NAME:Platform}
