CREATE TABLE ltis_ownr_info
(
    ownr_seq           BIGINT NOT NULL COMMENT '소유자SEQ',
    judg_seq           BIGINT NOT NULL COMMENT '재결일련번호',
    ownr_intr_nm       VARCHAR(255) COMMENT '소유자관계인명',
    ownr_intr_yn       VARCHAR(255) COMMENT '소유자관계인여부',
    delv_zip_no        VARCHAR(255) COMMENT '송달우편번호',
    delv_dtl_addr1     VARCHAR(255) COMMENT '송달상세주소1',
    delv_dtl_addr2     VARCHAR(255) COMMENT '송달상세주소2',
    depy_zip_no        VARCHAR(255) COMMENT '대리인우편번호',
    depy_dtl_addr1    VARCHAR(255) COMMENT '대리인상세주소1',
    depy_dtl_addr2    VARCHAR(255) COMMENT '대리인상세주소2',
    regt_no           VARCHAR(255) COMMENT '등기번호',
    ownr_intr_rmk     VARCHAR(255) COMMENT '소유자관계인비고',
    regt_year          VARCHAR(255) COMMENT '등기년도',
    bef_ownr_intr_seq VARCHAR(255) COMMENT '이전소유자관계인일련번호',
    represent_yn      VARCHAR(3) COMMENT '대표 여부',
    agree_yn          VARCHAR(3) COMMENT '동의 여부',
    add_dt1           DATE         COMMENT '협의만료일,현금청산만료일',
    add_dt2           DATE         COMMENT '재결청구일',
    add_dt3           DATE         COMMENT '수용신청일',
    ownr_intr_nm_seq  BIGINT COMMENT '소유자 동명이인 구분자',
    mod_dt            DATE COMMENT '수정일시',
    created_time      DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일',
    updated_time      DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    PRIMARY KEY (OWNR_SEQ, JUDG_SEQ)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='소유자 정보';

CREATE TABLE ltis_recm_info
(
    recm_advc_seq    BIGINT NOT NULL COMMENT '추천상담일련번호',
    judg_seq        BIGINT NOT NULL COMMENT '재결일련번호',
    grp_div_cd       VARCHAR(250) COMMENT '조구분코드',
    comp_cd         VARCHAR(50) COMMENT '법인코드',
    comy_abbv        VARCHAR(50) COMMENT '법인약어',
    recm_req_dt              DATE COMMENT '추천의뢰 요청 일시',
    recm_req_sbmt_dt         DATE COMMENT '추천의뢰 제출 일시',
    case_no          VARCHAR(250) COMMENT '감정평가서 번호',
    rwrd_prce              BIGINT COMMENT '보상가액',
    recm_advc_rmk   VARCHAR(250) COMMENT '추천상담 비고',
    prce_dt                  DATE COMMENT '가격시점',
    prgs_stat_cd     VARCHAR(250) COMMENT '진행상태코드',
    appr_path        VARCHAR(250) COMMENT '감정평가서경로',
    appr_inst_info    VARCHAR(250) COMMENT '평가기관정보',
    rept_mod_req_dt           DATE COMMENT '조서변경요청일시',
    coms_pay_yn       VARCHAR(250) COMMENT '수수료납부여부',
    ichr_apps_lics_no  VARCHAR(250) COMMENT '담당평가사자격번호',
    appr_email       VARCHAR(250) COMMENT '평가사이메일',
    appr_nm         VARCHAR(250) COMMENT '평가사명',
    appr_offc_nm     VARCHAR(250) COMMENT '평가사사무소명',
    appr_offc_addr   VARCHAR(250) COMMENT '평가사사무소주소',
    appr_dtl_addr    VARCHAR(250) COMMENT '평가사사무소상세주소',
    appr_ofce_phon_no VARCHAR(250) COMMENT '평가사사무소전화번호',
    appr_phon_no     VARCHAR(250) COMMENT '평가사연락처',
    appr_ofce_faxno  VARCHAR(250) COMMENT '평가사사무소FAX번호',
    recm_req_prce_dt         DATE COMMENT '추천의뢰 가격시점',
    mod_dt                   DATE COMMENT '수정일시',
    created_time      DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일',
    updated_time      DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    PRIMARY KEY (recm_advc_seq, judg_seq)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='평가법인정보';

CREATE TABLE ltis_rept_info (
    rept_seq             BIGINT                             NOT NULL COMMENT '조서일련번호',
    judg_seq             BIGINT                             NOT NULL COMMENT '재결일련번호',
    rept_lst_seq          BIGINT COMMENT '조서목록일련번호',
    sido_gungu_cd         VARCHAR(255) COMMENT '시군구코드',
    domyri_cd             VARCHAR(255) COMMENT '동면리코드',
    mont_div_cd           VARCHAR(255) COMMENT '산구분코드',
    main_strt_no          VARCHAR(255) COMMENT '본번',
    sub_strt_no          VARCHAR(255) COMMENT '부번',
    strt_other            VARCHAR(255) COMMENT '번외',
    rept_addr            VARCHAR(255) COMMENT '조서주소',
    area_amot             DECIMAL(23, 4) COMMENT '면적및수량',
    obst_kind_nm          VARCHAR(255) COMMENT '지장물종류명',
    obst_stuc1_nm         VARCHAR(255) COMMENT '지장물구조1',
    obst_stuc2_nm         VARCHAR(255) COMMENT '지장물구조2',
    bef_calc_cd           VARCHAR(255) COMMENT '이전계산코드',
    frst_comp_calc_cd     VARCHAR(255) COMMENT '법인A계산코드',
    secd_comp_calc_cd     VARCHAR(255) COMMENT '법인B계산코드',
    thrd_comp_calc_cd    VARCHAR(255) COMMENT '법인C계산코드',
    comp_avrg_calc_cd     VARCHAR(255) COMMENT '법인평균계산코드',
    judg_calc_cd         VARCHAR(255) COMMENT '재결계산코드',
    bef_unit_cost        BIGINT COMMENT '이전단가',
    frst_comp_unit_cost  BIGINT COMMENT '법인A단가',
    secd_comp_unit_cost  BIGINT COMMENT '법인B단가',
    thrd_comp_unit_cost BIGINT COMMENT '법인C단가',
    comp_avrg_unit_cost  BIGINT COMMENT '법인평균단가',
    judg_unit_cost      BIGINT COMMENT '재결단가',
    rights_nm            VARCHAR(255) COMMENT '권리명',
    sfce_rights_yn       VARCHAR(255) COMMENT '구분지상권여부',
    land_obst_kind_cd    VARCHAR(255) COMMENT '토지지장물종류코드',
    rept_lst_bef_seq       BIGINT COMMENT '조서목록이전일련번호',
    area_unit             VARCHAR(255) COMMENT '면적및단가',
    obst_stuc1_cd         VARCHAR(255) COMMENT '지목코드(공부상지목)',
    obst_stuc2_cd         VARCHAR(255) COMMENT '지목코드(이용상황)',
    omit_yn              VARCHAR(255) COMMENT '누락물 여부(0:아니오 1:예)',
    mod_dt               DATE COMMENT '수정일시',
    created_time         DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일',
    updated_time         DATETIME COMMENT '수정일',
    PRIMARY KEY (rept_seq, judg_seq, rept_lst_seq)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='조서 정보';

CREATE TABLE ltis_rept_ownr_info (
     rept_ownr_intr_seq    BIGINT NOT NULL COMMENT '조서관계인소유자일련번호',
     rept_seq             BIGINT NOT NULL COMMENT '조서일련번호',
     judg_seq             BIGINT NOT NULL COMMENT '재결일련번호',
     ownr_intr_yn         VARCHAR(255) COMMENT '소유자관계인여부',
     ownr_seq             BIGINT COMMENT '소유자일련번호',
     intr_seq             BIGINT COMMENT '관계인일련번호',
     intr_rights_nm       VARCHAR(255) COMMENT '관계인권리명',
     land_shre            VARCHAR(255) COMMENT '지분',
     bef_amt              BIGINT COMMENT '이전금액',
     frst_comp_amt        BIGINT COMMENT '법인A금액',
     secd_comp_amt        BIGINT COMMENT '법인B금액',
     thrd_comp_amt        BIGINT COMMENT '법인C금액',
     comp_avrg_amt        BIGINT COMMENT '법인평균금액',
     judg_amt             BIGINT COMMENT '재결금액',
     ownr_regt_seq        BIGINT COMMENT '소유자등기번호',
     intr_regt_seq        BIGINT COMMENT '관계인등기번호',
     bef_rept_ownr_intr_seq VARCHAR(255) COMMENT '사업시행자 조서관계인소유자일련번호(si_rept_ownr_intr)',
     add_charge_yn        VARCHAR(255) COMMENT '지연가산금계산여부',
     judg_unit_cost       BIGINT COMMENT '재결단가',
     omit_yn              VARCHAR(255) COMMENT '누락물 여부(0:아니오 1:예)',
     judg_calc_cd          VARCHAR(255) COMMENT '재결계산코드',
     rept_ownr_intr_rmk    VARCHAR(255) COMMENT '조서별 소유자관계인 비고',
     mod_dt               DATE COMMENT '수정일시',
     created_time         DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일',
     updated_time         DATETIME COMMENT '수정일',
     PRIMARY KEY (rept_ownr_intr_seq, rept_seq, judg_seq)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='조서소유자맵핑정보';

create table ltis_pnu
(
    judg_seq      bigint       NOT NULL COMMENT '재결일련번호',
    pnu           VARCHAR(20)  NOT NULL COMMENT 'PNU',
    sido_gungu_cd VARCHAR(5)   NOT NULL COMMENT '시군구코드',
    domyri_cd     VARCHAR(5)   NOT NULL COMMENT '동면리코드',
    mont_div_cd   VARCHAR(1)   NOT NULL COMMENT '산구분코드',
    main_strt_no  VARCHAR(4)   NOT NULL COMMENT '본번',
    sub_strt_no   VARCHAR(4)   NOT NULL COMMENT '부번',
    addr          VARCHAR(150) NOT NULL COMMENT '조서주소',
    created_time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
    updated_time  DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
    PRIMARY KEY (judg_seq, pnu),
    FOREIGN KEY (judg_seq) references ltis_status (judg_seq)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT = 'PNU';